1.Study introduction:
Firstly, participants underwent a series of laser stimulations of varying intensities. The experimenters determined the energy intensities corresponding to average scores of 4 and 7 points among the participants. Subsequently, each participant received a fixed-intensity laser stimulation approximately every 20 seconds, constituting one block of 40 trials, with half being high intensity and half low intensity. There were a total of 4 blocks, resulting in 160 stimulations in total. During this period, participants provided pain ratings ranging from 0 to 10. A rating of 0 indicated no sensation, 4 denoted the onset of pain perception, 6 represented moderate pain, 8 indicated severe pain, and 10 signified intolerable pain.
2.Participant task information(description of the experiment):
Participants received laser stimulation and used a computer mouse to click on the appropriate position on the screen, corresponding to a scale of 0 to 10.
3.Participant instructions(as exact as possible):
Participants were instructed to focus their attention on the laser stimuli, keep their eyes open, and fixate their gaze on the cross displayed on the screen. Following each laser stimulation, there was a 3-second pause. Subsequently, participants used the computer screen and keyboard to assess the intensity of pain within a 5-second time window. The subsequent trial commenced randomly within 1-3 seconds after the rating was provided.
4.References and links:
Bi Y, Liu X, Zhao X, et al. Enhancing pain modulation: the efficacy of synchronous combination of virtual reality and transcutaneous electrical nerve stimulation. General Psychiatry 2023;36:e101164. doi:10.1136/gpsych-2023-101164.
5.Comments:
In the raw data, "32" is used to represent "s32","64" is used to represent "s64".